leptonic EWK SUSY + susy interface updates
CERN-PH-CMG/cmgtools-lite pull request #142
Opened 2016-11-23 20:46 UTC by cheidegg

to be merged BEFORE the JEC PR

2016-11-24 09:15 UTC, gpetruc requested changes
I leave to @peruzzim to review the changes to run_susyMultilepton_cfg.py.
The rest seems to be fine after you fix the other things I have commented on.

2016-11-24 09:15 UTC, gpetruc commented on TTHAnalysis/macros/prepareEventVariablesFriendTree.py
> +MODULES += multiModules
Don't include them here, load them with -I

2016-11-24 09:15 UTC, gpetruc commented on RootTools/python/samples/triggers_13TeV_DATA2016.py
> -triggers_doubleele33  = ['HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v*']
Don't delete triggers from alphaT.

2016-11-24 09:30 UTC, gpetruc approved these changes

2016-11-24 09:58 UTC, peruzzim requested changes

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +ttHLepSkim.allowLepTauComb = True
To be removed (should be false for ttH and SOS, already set to true inside an if later)

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    susyCoreSequence.insert(susyCoreSequence.index(ttHLepSkim)+1,globalSkim)
First ttHLepSkim, then one looks for where ttHLepSkim is. It should be the opposite.

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    'DoubleMu' : triggers_mumu_iso ,
remove space

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    'DoubleMuNoIso' : triggers_mumu_noniso + triggers_mu27tkmu8,
to be verified why these triggers are not added to the already existing lists

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    'htall' : triggers_pfht
Please use more similar name like simply HT

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    del susyMultilepton_collections["discardedJets"]
I see that the modification to the cleaning of jets with leptons is in #143. Should be ok when both are merged, to be verified.

2016-11-24 09:58 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    processing = "Run2016B-23Sep2016-v2"; short = "Run2016B_23Sep2016_v2"; run_ranges = [(272760,273017)]; useAAA=True; # -v2 starts from 272760 to 273017
Not sure we need run ranges here, datasets are already mutually exclusive. Queries with run range are slower and should be avoided if possible.

2016-11-25 09:27 UTC, cheidegg commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    'htall' : triggers_pfht
This is a name already used in

2016-11-25 09:36 UTC, cheidegg commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
> +    'DoubleMuNoIso' : triggers_mumu_noniso + triggers_mu27tkmu8,
see https://github.com/CERN-PH-CMG/cmgtools-lite/blob/d2b37af6e46ff8c74fe6b919fd023f943f8f945b/RootTools/python/samples/triggers_13TeV_DATA2016.py#L159

2016-11-28 10:27 UTC, peruzzim approved these changes

2016-11-30 16:51 UTC, gpetruc commented
Hi @cheidegg: do we need to have https://github.com/CERN-PH-CMG/cmg-cmssw/pull/677 merged before this one, or not? 
That PR needs fixes.

2016-12-07 16:22 UTC, gpetruc requested changes
One last fix is needed

2016-12-07 16:22 UTC, gpetruc commented on TTHAnalysis/python/analyzers/globalEventSkimmer.py
> +class globalSkimmer( Analyzer ):
it should be called `globalEventSkimmer`, for consistency with the file name and with the name used in `susyCore_modules_cff` (which has `from CMGTools.TTHAnalysis.analyzers.globalEventSkimmer import globalEventSkimmer`)

2016-12-08 10:20 UTC, gpetruc approved these changes

2016-12-08 10:24 UTC, merged