add new JECs and update code
CERN-PH-CMG/cmgtools-lite pull request #143
Opened 2016-11-23 20:46 UTC by cheidegg

from commit dad137e3a148cdf2f3d6d690aeca8293fd2bd8a4
new JEC files AND some code updates
to be merged ON TOP of leptonic EWK SUSY PR #142

2016-11-24 09:22 UTC, peruzzim requested changes
tar.gz files are not needed and should not be added to the repository.
Also, please remove the hidden files in the JEC directory (._Spring16_25nsV8BCD_DATA_L2L3Residual_AK4PFchs.txt etc.).
Some other modifications/additions are duplicate with #142.

2016-11-24 09:22 UTC, peruzzim commented on TTHAnalysis/cfg/run_susyMultilepton_cfg.py
>  # Lepton Skimming
This and other modifications to configuration files are also in #142. It should not be the case... if left like this, one will need to be careful to merge correctly.

2016-11-24 09:22 UTC, peruzzim commented on TTHAnalysis/data/json/Cert_271036-283685_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt
> +{"273158": [[1, 1279]],
If we really need to add a JSON, we should have only the latest version.

2016-11-24 10:06 UTC, mariadalfonso commented
@cheidegg can you add the .db file of the Spring16_25nsV8 so that we have a complete set ?

2016-11-24 10:07 UTC, mariadalfonso commented
@cheidegg 
the JSON file can be remove, and maybe point to the original in your cfg  i.e. ?
/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Cert_271036-276811_13TeV_PromptReco_Collisions16_JSON_NoL1T.txt

2016-11-28 10:30 UTC, peruzzim approved these changes

2016-11-28 20:26 UTC, mariadalfonso commented
@peruzzim @gpetruc 
I would suggest to wait to merge this PR, as the V8 JEC are going to be depreccted  (as buggy)
V10 are going to be releases very very soon 
https://github.com/cms-jet/JECDatabase/tree/master/textFiles

2016-12-06 11:06 UTC, peruzzim commented
@mariadalfonso as the analyzers have already shared this branch and used it (even if JECs are buggy) for some internal results, I would propose to merge it and ensure that V8 is not used by default

2016-12-08 10:45 UTC, gpetruc commented
Hi Constantin, can you quickly fix the conflict?

2016-12-08 12:02 UTC, gpetruc commented
Uhm, after some look, I think this PR is out of sync with some fixes, e.g. the first modification of https://github.com/CERN-PH-CMG/cmgtools-lite/pull/142/commits/e4ba1a9a5f9853e5f844fe239d2154d0ae942868 or the changes and the change of way the run-dependent JECs are configured.

2016-12-08 12:55 UTC, gpetruc commented
I will merge this afternoon manually but leave the default JECs to V6 for susyCore.
I leave to you to fix in a future local PR the running with analysis == susy.

2016-12-08 15:02 UTC, merged