Update to the Summer16 sample file in RootTools
CERN-PH-CMG/cmgtools-lite pull request #172
Opened 2017-01-31 14:29 UTC by danbarto

2017-02-09 11:19 UTC, gpetruc requested changes

2017-02-09 11:19 UTC, gpetruc commented on RootTools/python/samples/samples_13TeV_RunIISummer16MiniAODv2.py
> +tWnunu = kreator.makeMCComponent("tWnunu", "/ST_tWnunu_5f_LO_13TeV-MadGraph-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM", "CMS", ".*root", 0.01123
can you add this below in the `SingleTop` list?

2017-02-09 11:19 UTC, gpetruc commented on RootTools/python/samples/samples_13TeV_RunIISummer16MiniAODv2.py
> +QCD_Pt30to50          = kreator.makeMCComponent("QCD_Pt30to50"         , "/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIA
please add this under `QCDPt`

2017-02-13 10:32 UTC, danbarto commented on RootTools/python/samples/samples_13TeV_RunIISummer16MiniAODv2.py
> +tWnunu = kreator.makeMCComponent("tWnunu", "/ST_tWnunu_5f_LO_13TeV-MadGraph-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM", "CMS", ".*root", 0.01123
Done

2017-02-13 10:32 UTC, danbarto commented on RootTools/python/samples/samples_13TeV_RunIISummer16MiniAODv2.py
> +QCD_Pt30to50          = kreator.makeMCComponent("QCD_Pt30to50"         , "/QCD_Pt_30to50_TuneCUETP8M1_13TeV_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIA
Done

2017-02-13 10:34 UTC, danbarto commented
I did the requested changes.
Additionally, I fixed the single top cross sections that were wrong:
- tWch_noFullyHad used the inclusive xsec -> solved
- TBar_tch_powheg used the T_tch_powheg xsec -> solved

2017-02-14 07:50 UTC, gpetruc approved these changes

2017-02-14 08:54 UTC, merged