Add sample skeletons
CERN-PH-CMG/cmgtools-lite pull request #208
Opened 2018-01-22 17:12 UTC by mmarionncern

On top of  #207 , contains the skeleton of the sample files copied from 2017, as well as the findSample script that looks into the DB to create a new sample file with new samples inside

2018-01-23 16:30 UTC, gpetruc commented
Why do we need a new samples file for the same RunIISummer16 MiniAOD v2 processing?

2018-01-23 16:31 UTC, gpetruc commented on RootTools/python/samples/samples_13TeV_RunIISummer16Legacy.py
> +TT_pow = kreator.makeMCComponent("TTbar", "/TT_TuneCUETP8M1_13TeV-powheg-pythia8//MINIAODSIM", "CMS", ".*root", 831.762)
missing part of the dataset name

2018-01-23 17:28 UTC, gpetruc requested changes
also samples_13TeV_RunIISummer16Legacy_ExtraSamples.py is buggy (just loading it with python shows that there are undefined samples)

2018-01-23 17:28 UTC, gpetruc commented on RootTools/python/samples/samples_13TeV_RunIISummer16Legacy.py
> +WZTo1L3Nu,
this is not defined

2018-01-23 17:28 UTC, gpetruc commented on RootTools/python/samples/samples_13TeV_RunIISummer16Legacy.py
> +mcSamples = TTs + SingleTop + VJets + DYJetsM50HT + DYJetsM5to50HT + WJetsToLNuHT + WNJets + GJetsHT + ZJetsToNuNuHT + QCDHT + QCDPtbcToE + QCDPt + QCDPtEMEnriched + [QCD_Mu15] + QCD_Mu5 +  DiBosons
`DYJetsM50HT` , `DYJetsM5to50HT` ,`WJetsToLNuHT`, `WNJets`, `GJetsHT`, `ZJetsToNuNuHT`, `QCDHT`, `QCDPt` not defined

2018-02-05 08:51 UTC, mmarionncern commented
@gpetruc This is rather a template that will be updated once we have the samples rather than a new sample file for RunIISummer16. I can change the name to make more explicit if you wish

2018-02-05 17:01 UTC, gpetruc commented
Uhm, it's still not clear to me what's the goal.
For Fall17, we have a sample file that is being populated with new samples.
For the legacy 2016, I would wait until the legacy re-miniAOD is ongoing and first samples arrive before adding a new sample file.
So, I would prefer to close this now, and re-open it when it will be needed.

2018-02-06 08:16 UTC, mmarionncern commented
No problem for me, I think it was wanted by @peruzzim, but maybe I misunderstood. If both of you agree, I close this one and wait till we have the full Fall17 picture

2018-02-06 08:19 UTC, closed without merging